name: CI

on:
  schedule:
  - cron: 0 15 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install pipenv and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv --upgrade-strategy=only-if-needed
        pipenv install --dev

    - name: Build and commit
      run: |
        git config user.name "circled9-bot"
        git config user.email "matsui+bot@kaffeine.jp"
        git remote set-url origin https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
        git checkout develop
        pipenv run main
        git add dist
        git commit -m "daily update"
        git push origin develop || true
